# @package agent
_target_: agent.potil.POTILAgent
root_dir: ${root_dir}
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 0
hidden_dim: ${suite.hidden_dim}
feature_dim: 50
stddev_schedule: 0.1 #'linear(1.0,0.1,500000)'
stddev_clip: 0.3
augment: False
rewards: sinkhorn_cosine
sinkhorn_rew_scale: 200
update_target_every: 10000
use_trunk_target: False
trunk_target_teacher: actor
auto_rew_scale: True
auto_rew_scale_factor: 10
suite_name: ${suite.name}
obs_type: ${obs_type}
bc_weight_type: ${bc_weight_type}
bc_weight_schedule: 'linear(1.0,0.1,20000)'
use_encoded_repr: ${store_repr}
temperature_scaled: False
temperature: 0.1
cost2reward: linear
beta: 100.0   # used when cost to reward funtion is exp(- beta * cost)

# encoder
backbone: resnet
embedding_name: mocov2-resnet50
freeze: true
fp16: true