name: pvm
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - pip:
    - protobuf==3.20.1
    - termcolor==1.1.0
    - dm_control
    - gym==0.22.0
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - POT==0.7.0
    - wandb==0.13.4
    - iopath==0.1.10
