# @package suite
defaults:
  - _self_
  - kitchen_task@_global_: turn_knob

suite: kitchen

name: 'kitchen'

# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
hidden_dim: 1024

# train settings
num_train_frames: 1100000
num_seed_frames: 12000

# eval
eval_every_frames: 20000
num_eval_episodes: 10

# snapshot
save_snapshot: true
save_buffer: false

task_make_fn:
  _target_: suite.kitchen.make
  name: ${task_name}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
